shell.program = "C:\\Program Files\\Git\\bin\\bash.exe"
shell.args = ["--login"]

working_directory = "C:\\Users\\User"

[window]
dimensions.columns = 160
dimensions.lines = 40

padding.x = 5
padding.y = 5
opacity = 1
blur = true
dynamic_title = true
resize_increments = false

[font]
normal.family = "JetBrainsMono Nerd Font"
normal.style = "Regular"

bold.family = "JetBrainsMono Nerd Font"
bold.style = "Bold"

italic.family = "JetBrainsMono Nerd Font"
italic.style = "Italic"

bold_italic.family = "JetBrainsMono Nerd Font"
bold_italic.style = "Bold Italic"

size = 12

[selection]
save_to_clipboard = true

[terminal]

osc52 = "CopyPaste"

