[shell]
program = "/bin/zsh"
args = ["-l"]

[window]
opacity = 0.7
blur = true
dynamic_title = true
padding.x = 5
padding.y = 5
decorations = "Buttonless"

[font]
normal.family = "JetBrainsMono Nerd Font"
normal.style = "Regular"

bold.family = "JetBrainsMono Nerd Font"
bold.style = "Bold"

italic.family = "JetBrainsMono Nerd Font"
italic.style = "Italic"

bold_italic.family = "JetBrainsMono Nerd Font"
bold_italic.style = "Bold Italic"

size = 18
